CREATE TABLE TA_DOCUMENTO(
<<<<<<< HEAD
    ID_DOCUMENTO NUMBER,
    NOMBRE       VARCHAR(100),
    APELLIDO     VARCHAR(100),
    DOCUMENTO    CLOB,
    CORREO       VARCHAR(100),
    STATUS       NUMBER,
    NUM_EMPLEADO NUMBER,
    CONSTRAINT   PK_DOCUMENTO 
    PRIMARY KEY  (ID_DOCUMENTO)
=======
    ID_DOCUMENTO   NUMBER,
    NOMBRE         VARCHAR(100),
    APELLIDO       VARCHAR(100),
    NUM_EMPLEADO   NUMBER,
    DOCUMENTO      CLOB,
    CORREO         VARCHAR(100),
    STATUS         NUMBER,
    CONSTRAINT     PK_DOCUMENTO 
    PRIMARY KEY    (ID_DOCUMENTO)
>>>>>>> 09b4939996e47e38b0356bef3660bf97619f1d53
);
