CREATE TABLE TA_EMPLEADO (
    ID_EMPLEADO   NUMBER,
    DOCUMENTO     CHAR(8),
    APELLIDO      VARCHAR2(100),
    NOMBRE        VARCHAR2(100),
    SECCION       VARCHAR2(100),
    SUELDO        NUMBER(8,2),
    CONSTRAINT    PK_EMPLEADO 
    PRIMARY KEY   (ID_EMPLEADO)
);