CREATE TABLE TA_EMPLEADO (
<<<<<<< HEAD
    ID_EMPLEADO   NUMBER,
    DOCUMENTO     CHAR(8),
    APELLIDO      VARCHAR2(100),
    NOMBRE        VARCHAR2(100),
    SECCION       VARCHAR2(100),
    SUELDO        NUMBER(8,2),
    NUM_EMPLEADO  NUMBER,
    CONSTRAINT    PK_EMPLEADO 
    PRIMARY KEY   (ID_EMPLEADO)
=======
    ID_EMPLEADO    NUMBER,
    DOCUMENTO      CHAR(8),
    APELLIDO       VARCHAR2(100),
    NOMBRE         VARCHAR2(100),
    SECCION        VARCHAR2(100),
    NUM_EMPLEADO   NUMBER,
    SUELDO         NUMBER(8,2),
    CONSTRAINT     PK_EMPLEADO 
    PRIMARY KEY    (ID_EMPLEADO)
>>>>>>> 09b4939996e47e38b0356bef3660bf97619f1d53
);
