CREATE OR REPLACE PACKAGE BODY PA_COMPANIA AS
    PROCEDURE SP_GETCOMPANIA(
        REC_CURSOR OUT SYS_REFCURSOR
    )AS
    BEGIN
        OPEN REC_CURSOR FOR
            SELECT * FROM TA_COMPANIA
            ORDER BY ID_COMPANIA;
    END SP_GETCOMPANIA;

    PROCEDURE SP_SETCOMPANIA(
        PA_EMPLEADO    IN VARCHAR2,
        PA_NOMBRE      IN VARCHAR2,
        PA_APELLIDO    IN VARCHAR2,
        PA_RFC         IN VARCHAR2,
        PA_EMPRESA     IN VARCHAR2,
        PA_NOTA        IN CLOB,
        PA_TRIMESTRE   IN VARCHAR2
    )AS
        v_empleado NUMBER;
        v_trimestre NUMBER;
    BEGIN
        IF PA_NOMBRE IS NULL OR PA_APELLIDO IS NULL OR PA_EMPLEADO IS NULL OR
        PA_EMPRESA IS NULL OR PA_NOTA IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN REGISTROS VACÍOS');
        ELSIF NOT (REGEXP_LIKE(PA_EMPLEADO, '^[0-9]+$') AND REGEXP_LIKE(PA_TRIMESTRE, '^[0-9]+$')) THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL NUMERO DE EMPLEADO O TRIMESTRE INGRESADO ES INVÁLIDO');
        ELSE
            v_empleado := TO_NUMBER(PA_EMPLEADO);
            v_trimestre := TO_NUMBER(PA_TRIMESTRE);
            UPDATE TA_COMPANIA SET NUM_EMPLEADO=v_empleado, RFC=PA_RFC, COMPANIA=PA_EMPRESA,
            NOTA=PA_NOTA, TRIMESTRE=v_trimestre WHERE UPPER(NOMBRE) = UPPER(PA_NOMBRE) AND
            UPPER(APELLIDO) = UPPER(PA_APELLIDO);
        END IF;
    END SP_SETCOMPANIA;

    PROCEDURE SP_GETNOMBRE(
        REC_CURSOR     OUT SYS_REFCURSOR,
        PA_NOMBRE      IN VARCHAR2
    ) AS
    BEGIN
        IF PA_NOMBRE IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN REGISTROS VACÍOS');
        ELSE
            OPEN REC_CURSOR FOR
                SELECT * FROM TA_COMPANIA 
                WHERE UPPER(NOMBRE) = UPPER(PA_NOMBRE)
                ORDER BY ID_COMPANIA;
        END IF;
    END SP_GETNOMBRE;
END PA_COMPANIA;