CREATE OR REPLACE PACKAGE PA_DOCUMENTO AS
    PROCEDURE SP_GETDOCUMENTOS(
        REC_CURSOR OUT SYS_REFCURSOR
    );
    
    PROCEDURE SP_GETSTATUS(
        REC_CURSOR     OUT SYS_REFCURSOR
    );
    
    PROCEDURE SP_SETDOCUMENTOS(
        PA_NOMBRE      IN VARCHAR2,
        PA_APELLIDO    IN VARCHAR2,
        PA_CORREO      IN VARCHAR2,
        PA_STATUS      IN VARCHAR2
    );

    PROCEDURE SP_UPDTDOCUMENTOS(
        PA_NOMBRE      IN VARCHAR2,
        PA_DOCUMENT    IN CLOB,
        PA_STATUS      IN VARCHAR2
    );
END PA_DOCUMENTO;