CREATE OR REPLACE PACKAGE BODY PA_DOCUMENTO AS
    PROCEDURE SP_GETDOCUMENTOS(
        REC_CURSOR OUT SYS_REFCURSOR
    )AS
    BEGIN
        OPEN REC_CURSOR FOR
            SELECT * FROM TA_DOCUMENTO
            ORDER BY ID_DOCUMENTO;
    END SP_GETDOCUMENTOS;

    PROCEDURE SP_GETSTATUS(
        REC_CURSOR OUT SYS_REFCURSOR
    )AS
        v_status NUMBER:=0;
    BEGIN        
        OPEN REC_CURSOR FOR
            SELECT * FROM TA_DOCUMENTO
            WHERE STATUS=v_status ORDER 
            BY ID_DOCUMENTO;
    END SP_GETSTATUS;
    
    PROCEDURE SP_SETDOCUMENTOS(
        PA_NOMBRE      IN VARCHAR2,
        PA_APELLIDO    IN VARCHAR2,
        PA_CORREO      IN VARCHAR2,
        PA_STATUS      IN VARCHAR2
    )AS
        v_status NUMBER;
    BEGIN
        IF PA_STATUS IS NULL OR PA_NOMBRE IS NULL OR PA_APELLIDO IS NULL OR
        PA_CORREO IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN REGISTROS VACÍOS');
        ELSIF NOT REGEXP_LIKE(PA_STATUS, '^[0-9]+$') THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL STATUS INGRESADO ES INVÁLIDO');
        ELSE
            v_status := TO_NUMBER(PA_STATUS);
            UPDATE TA_DOCUMENTO SET CORREO=PA_CORREO, STATUS=PA_STATUS WHERE
            UPPER(NOMBRE) = UPPER(PA_NOMBRE) AND UPPER(APELLIDO) = UPPER(PA_APELLIDO);            
        END IF;
    END SP_SETDOCUMENTOS;
    
    PROCEDURE SP_UPDTDOCUMENTOS(
        PA_NOMBRE      IN VARCHAR2,
        PA_DOCUMENT    IN CLOB,
        PA_STATUS      IN VARCHAR2
    )AS
        v_status NUMBER;
        v0_status NUMBER:=0;
    BEGIN
        IF PA_NOMBRE IS NULL OR PA_STATUS IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN REGISTROS VACÍOS');
        ELSIF NOT REGEXP_LIKE(PA_STATUS, '^[0-9]+$') THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL STATUS INGRESADO ES INVÁLIDO');
        ELSE
            v_status := TO_NUMBER(PA_STATUS);
            UPDATE TA_DOCUMENTO SET DOCUMENTO=PA_DOCUMENT, STATUS=v_status
            WHERE UPPER(NOMBRE) = UPPER(PA_NOMBRE) AND STATUS=v0_status;
        END IF;
    END SP_UPDTDOCUMENTOS;
END PA_DOCUMENTO;

