CREATE OR REPLACE PACKAGE BODY PA_EMPLEADOS AS

    PROCEDURE SP_GETEMPLEADO(
        REC_CURSOR OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN REC_CURSOR FOR
            SELECT * FROM TA_EMPLEADO
            ORDER BY ID_EMPLEADO;
    END SP_GETEMPLEADO;
    
    PROCEDURE SP_INSERT_EMPLEADOS(
        PA_DOCUMENTO IN VARCHAR2,
        PA_APELLIDO  IN VARCHAR2,
        PA_NOMBRE    IN VARCHAR2,
        PA_SECCION   IN VARCHAR2,
        PA_SUELDO    IN VARCHAR2
    ) AS
        v_sueldo NUMBER;
    BEGIN
        -- Validaciones
        IF PA_DOCUMENTO IS NULL OR PA_APELLIDO IS NULL OR PA_NOMBRE IS NULL OR
           PA_SECCION IS NULL OR PA_SUELDO IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN REGISTROS VACÍOS');
        ELSIF NOT REGEXP_LIKE(PA_SUELDO, '^[0-9]+$') THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL SUELDO INGRESADO ES INVÁLIDO');
        ELSE
            v_sueldo := TO_NUMBER(PA_SUELDO);
            UPDATE TA_EMPLEADO SET DOCUMENTO=PA_DOCUMENTO, SECCION=PA_SECCION,
            SUELDO=v_sueldo WHERE UPPER(NOMBRE) = UPPER(PA_NOMBRE) AND
            UPPER(APELLIDO) = UPPER(PA_APELLIDO);

            DBMS_OUTPUT.PUT_LINE('¡REGISTRO EXITOSO!');
        END IF;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20003, '¡EL DOCUMENTO A REGISTRAR YA EXISTE!');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20004, '¡ERROR INESPERADO: ' || SQLERRM || '!');
    END SP_INSERT_EMPLEADOS;
    
    PROCEDURE SP_UPDATE_EMPLEADO(
        PA_ID      IN VARCHAR2,
        PA_SECCION IN VARCHAR2,
        PA_SUELDO  IN VARCHAR2
    ) AS
        v_id NUMBER;
        v_sueldo NUMBER;
    BEGIN
        IF PA_ID IS NULL OR PA_SECCION IS NULL OR PA_SUELDO IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001,'NO SE PERMITEN REGISTROS VACÍOS');
        ELSIF NOT (REGEXP_LIKE(PA_SUELDO, '^[0-9]+$') AND REGEXP_LIKE(PA_ID, '^[0-9]+$')) THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL SUELDO O ID INGRESADOS SON INVÁLIDOS, SOLO SE PERMITEN NÚMEROS');
        ELSE
            v_id := TO_NUMBER(PA_ID);
            v_sueldo := TO_NUMBER(PA_SUELDO);
        
            UPDATE TA_EMPLEADO
            SET SECCION = PA_SECCION,
                SUELDO  = v_sueldo
            WHERE ID_EMPLEADO = v_id;
            DBMS_OUTPUT.PUT_LINE('¡ACTUALIZACIÓN EXITOSA!');
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20003, '¡EL EMPLEADO NO EXISTE!');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20004, '¡ERROR INESPERADO: ' || SQLERRM || '!');
    END SP_UPDATE_EMPLEADO;

    PROCEDURE SP_DEDUCCIONES(
        REC_CURSOR   OUT SYS_REFCURSOR,
        PA_NOMBRE    IN VARCHAR2
    )AS
    BEGIN
        OPEN REC_CURSOR FOR
            SELECT
                NOMBRE,                
                TO_CHAR(SUELDO * 3, 'FM999,999,999') AS SUELDO_BRUTO,    
                TO_CHAR(ROUND(SUELDO * 3 * 0.12, 2), 'FM999,999,999') AS ISR,
                TO_CHAR(ROUND(SUELDO * 3 * 0.05, 2), 'FM999,999,999') AS IMSS,  
                TO_CHAR(ROUND(SUELDO * 3 * 0.03, 2), 'FM999,999,999') AS FONDO_AHORRO,    
                TO_CHAR(
                    ROUND(
                        (SUELDO * 3)
                        - (SUELDO * 3 * 0.12)
                        - (SUELDO * 3 * 0.05)
                        - (SUELDO * 3 * 0.03), 2
                    ),
                    'FM999,999,999'
                )AS SUELDO_NETO
            FROM TA_EMPLEADO
            WHERE UPPER(nombre) = UPPER(PA_NOMBRE);
    END SP_DEDUCCIONES;

    PROCEDURE SP_IMPUESTOS(
        REC_CURSOR OUT SYS_REFCURSOR,
        PA_NOMBRE    IN VARCHAR2
    )AS
    BEGIN
        OPEN REC_CURSOR FOR
            SELECT    
                NOMBRE,    
                TO_CHAR(ROUND(SUELDO * 3 * 0.12, 2), 'FM999,999,999') AS ISR,
                TO_CHAR(ROUND(SUELDO * 3 * 0.05, 2), 'FM999,999,999') AS IMSS,
                TO_CHAR(ROUND((SUELDO * 3 * 0.12) + (SUELDO * 3 * 0.05), 2), 'FM999,999,999') AS TOTAL_IMPUESTOS
                FROM TA_EMPLEADO
            WHERE UPPER(NOMBRE) = UPPER(PA_NOMBRE);
    END SP_IMPUESTOS;
END PA_EMPLEADOS;