CREATE OR REPLACE PROCEDURE SP_UNIVERSAL(
    PA_NOMBRE IN VARCHAR2,
    PA_APELLIDO IN VARCHAR2
)AS
    BEGIN
    IF PA_NOMBRE IS NULL OR PA_APELLIDO IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN REGISTROS VACÍOS');
    ELSE
        INSERT INTO TA_EMPLEADO (APELLIDO, NOMBRE) VALUES (PA_APELLIDO, PA_NOMBRE);
        INSERT INTO TA_COMPANIA (APELLIDO, NOMBRE) VALUES (PA_APELLIDO, PA_NOMBRE);
        INSERT INTO TA_DOCUMENTO (APELLIDO, NOMBRE) VALUES (PA_APELLIDO, PA_NOMBRE);
    END IF;
END SP_UNIVERSAL;